### ISSUE TITLE
UI Suggestions

### ISSUE THREAD

**Issue by 96kyonkichi** [EngineerMark/OsuAchievedOverlay#15]
Hi, I am a total noob in github and I do not know how else to express my suggestions on the current version

I would like to suggest a little bigger and/or fonts as the text end up unreadable on a 720p live stream unless I make the overlay bigger than my osu game capture, which is a big no-no. Maybe if users could also change fonts, as osu default fonts suffer from readability issues themselves (i.e., confusing 2 and 9, preference for thicker fonts)

My most important suggestion to make is for users to be able to select which stat do they include and which do they not include. I've actually discovered this overlay when I was just looking how to include only my global and country rank so that I dont have to edit text placeholders of my profile rank before every start of my stream.

Otherwise, really neat overlay. Just that, again, I doubt if it will be readable at all when I have to fit my osu game capture and this overlay in one 720p sized screen without sacrificing readability.

**Comment by EngineerMark** [comment]
Hi! Thanks for the suggestion.

Indeed, I've been aware of the display issues.
In the current version it is just not adjustable at all.

I don't know if you attempted this, but in OBS you are able to render only (crop) a portion of the window (only works if the stats you want to show are next to each other obviously).

I'm already working on a rewrite of the tool in an actual engine rather than WPF. Perks of this is that resizing the window and changing tons of stuff in runtime is much easier (and thus fonts as well).
The release after 1.0.9 will be the move to the rewrite.
Although it may not be there right away, this is for sure something to include in one of the upcoming versions.

More information will be coming in the coming days or weeks.

**Comment by EngineerMark** [comment]
Update: For the foreseeable future, I won't implement font/scale settings. (The web aspect of it doesn't allow this as easily as I wanted to).

Resizable window fixes the scaling partially, as the font scales along resolution.

**Comment by EngineerMark** [comment]
Marking this as closed. Support might eventually be added, thing said above will do for now.
