### ISSUE TITLE
idk what's the issue and would like support for this 

### ISSUE THREAD

**Issue by Legitted** [EngineerMark/OsuAchievedOverlay#18]
![image](https://user-images.githubusercontent.com/47558620/139959242-6804ddd3-bf84-4113-b6d3-420b02e16603.png)

it dissapears whenever I use my scroll wheel and Idk how does this happen sorry for not elaborating good enough,I dont really get what is going on

**Comment by Legitted** [comment]
it doesnt break when using 1.0.9.1

**Comment by EngineerMark** [comment]
Pre 2.0.0 versions use a different rendering engine. I have switched to Chromium since.

It seems like CEF somehow messes up, though I haven't seen a browser (or cef application) break like that.
What GPU do you have (if Optimus, which GPU does osu!Achieved use)? Or specs in general.

I'm doubtful I can fix something like this, since it's highly likely an issue in Chromium (or the wrapper I use for C#) or in video drivers, but I will do some research on it.

**Comment by Legitted** [comment]
Hey sorry for the late reply I have 2 GPU 1 being 1050 ti and another one being  Intel UHD graphics 630

**Comment by Legitted** [comment]
ok I did some trolling the issue was literally just driver issue,I just reinstalled it xd so sorry for the problem
